-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-drop-unique-indices.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX nl_name;
DROP INDEX nl_main_page_active;

CREATE INDEX nl_name ON nl_newsletters (nl_name);

CREATE INDEX nl_main_page_active ON nl_newsletters (nl_main_page_id, nl_active);
